// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3ybjnznK8OD0dxd3qL8JbX-L9PYLSy9I',
    appId: '1:1060047492259:web:45227533e03d04608adb16',
    messagingSenderId: '1060047492259',
    projectId: 'fir-projectflutter-92572',
    authDomain: 'fir-projectflutter-92572.firebaseapp.com',
    storageBucket: 'fir-projectflutter-92572.appspot.com',
    measurementId: 'G-GRQEF4SR80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSHZ_onN-QTScVjVW7tseMtr8ybYSxc4s',
    appId: '1:1060047492259:android:d1cf8ab728556c378adb16',
    messagingSenderId: '1060047492259',
    projectId: 'fir-projectflutter-92572',
    storageBucket: 'fir-projectflutter-92572.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvwhwaNVkUEbm2XjxvOAkKUpzKMhYIWuE',
    appId: '1:1060047492259:ios:0d55c7d29046b5c48adb16',
    messagingSenderId: '1060047492259',
    projectId: 'fir-projectflutter-92572',
    storageBucket: 'fir-projectflutter-92572.appspot.com',
    iosBundleId: 'com.example.firebaseProjectFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvwhwaNVkUEbm2XjxvOAkKUpzKMhYIWuE',
    appId: '1:1060047492259:ios:b9b5ce70dd24321c8adb16',
    messagingSenderId: '1060047492259',
    projectId: 'fir-projectflutter-92572',
    storageBucket: 'fir-projectflutter-92572.appspot.com',
    iosBundleId: 'com.example.firebaseProjectFlutter.RunnerTests',
  );
}
